const mockData = [
  {
    "Incident ID": "001",
    "Title": "Mock Incident in Delhi",
    "Date of Incident": "2024-05-15",
    "Location": "New Delhi",
    "State": "Delhi",
    "Victim Community": "Dalit",
    "Incident Type": "Physical Assault",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/1",
    "Latitude": "28.6139",
    "Longitude": "77.2090"
  },
  {
    "Incident ID": "002",
    "Title": "Mock Incident in Mumbai",
    "Date of Incident": "2024-05-10",
    "Location": "Mumbai",
    "State": "Maharashtra",
    "Victim Community": "Adivasi",
    "Incident Type": "Discrimination",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/2",
    "Latitude": "19.0760",
    "Longitude": "72.8777"
  },
  {
    "Incident ID": "003",
    "Title": "Mock Incident in Bangalore",
    "Date of Incident": "2024-05-12",
    "Location": "Bangalore",
    "State": "Karnataka",
    "Victim Community": "Dalit",
    "Incident Type": "Violence",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/3",
    "Latitude": "12.9716",
    "Longitude": "77.5946"
  },
  {
    "Incident ID": "004",
    "Title": "Mock Incident in Chennai",
    "Date of Incident": "2024-05-08",
    "Location": "Chennai",
    "State": "Tamil Nadu",
    "Victim Community": "Dalit",
    "Incident Type": "Harassment",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/4",
    "Latitude": "13.0827",
    "Longitude": "80.2707"
  },
  {
    "Incident ID": "005",
    "Title": "Mock Incident in Kolkata",
    "Date of Incident": "2024-05-05",
    "Location": "Kolkata",
    "State": "West Bengal",
    "Victim Community": "Minority",
    "Incident Type": "Discrimination",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/5",
    "Latitude": "22.5726",
    "Longitude": "88.3639"
  },
  {
    "Incident ID": "006",
    "Title": "Mock Incident in Hyderabad",
    "Date of Incident": "2024-05-03",
    "Location": "Hyderabad",
    "State": "Telangana",
    "Victim Community": "Dalit",
    "Incident Type": "Violence",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/6",
    "Latitude": "17.3850",
    "Longitude": "78.4867"
  },
  {
    "Incident ID": "007",
    "Title": "Mock Incident in Jaipur",
    "Date of Incident": "2024-05-01",
    "Location": "Jaipur",
    "State": "Rajasthan",
    "Victim Community": "Adivasi",
    "Incident Type": "Discrimination",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/7",
    "Latitude": "26.9124",
    "Longitude": "75.7873"
  },
  {
    "Incident ID": "008",
    "Title": "Mock Incident in Ahmedabad",
    "Date of Incident": "2024-04-28",
    "Location": "Ahmedabad",
    "State": "Gujarat",
    "Victim Community": "Minority",
    "Incident Type": "Physical Assault",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/8",
    "Latitude": "23.0225",
    "Longitude": "72.5714"
  },
  {
    "Incident ID": "009",
    "Title": "Mock Incident in Lucknow",
    "Date of Incident": "2024-04-25",
    "Location": "Lucknow",
    "State": "Uttar Pradesh",
    "Victim Community": "Dalit",
    "Incident Type": "Violence",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/9",
    "Latitude": "26.8467",
    "Longitude": "80.9462"
  },
  {
    "Incident ID": "010",
    "Title": "Mock Incident in Bhopal",
    "Date of Incident": "2024-04-20",
    "Location": "Bhopal",
    "State": "Madhya Pradesh",
    "Victim Community": "Adivasi",
    "Incident Type": "Harassment",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/10",
    "Latitude": "23.2599",
    "Longitude": "77.4126"
  },
  {
    "Incident ID": "60fafeb1-480a-4223-ae9f-b6688992c591",
    "Title": "98 get life term for 2014 violence against Dalits in Karnataka - Times of India",
    "Date of Incident": "2014-01-15",
    "Location": "Karnataka",
    "State": "Karnataka",
    "Victim Community": "Dalit",
    "Incident Type": "Violence, Physical Assault",
    "Source Name": "Google News",
    "Source URL": "https://news.google.com/rss/articles/CBMiygFBVV95cUxQYnpOM29Id2paVWVSN0tSakl0TVlXUm5TYkJaOFlYYWR5UTUzQktYVi1WWlg1MWJYelFmYUxRY2pxMjFnVG5aUnVnT2liQjJIVFp2WWZDb0NYRVNId1UxQmc3M2ZuN2U0d2h4TWFYSWpJVHVhMllfOVprQ2pVN085Ul9zRXBxRGNuLUFmV2ZJSm1IdlRrWnJvZFZiOVVYcXhNNGZvdWtTNnA1M21BMS1NVTYtQ3lwNWRZcV9iN0JhY2xETmRuRnlyV0p30gHPAUFVX3lxTE9TeVF2a21ENk9vTkw1UUdDWm9adnVqcnFuYUhXeHBtcENYQ1dKc0J6aG9qakJoYjV6TWJkeWZ1enRjSUZ5SzdNaXAzVUdINVhPYkV5RFd5NVFONnkyTk1VUEtXMDlzRmFweUJQRC04YW1LSk9wc2lZaGl3SHFiVS1HbGozQlBER1Y3YXRobVZqQTh0UVRJVGVsUVpORk5nNGc4dmJCczdIeU5TRF9RVWwyd044alQtZnB6MVVsY3dxUDlHcmhxM2poVGMyOW9RYw?oc=5",
    "Latitude": "15.3173",
    "Longitude": "75.7139"
  },
  {
    "Incident ID": "131f7d08-2ceb-4023-97aa-5cdca29237a6",
    "Title": "NHRC takes suo motu cognisance over Dalit student's fingers chopped off by upper-caste boys in Thoothukudi - Maktoob Media",
    "Date of Incident": "2024-05-10",
    "Location": "Thoothukudi",
    "State": "Tamil Nadu",
    "Victim Community": "Dalit",
    "Incident Type": "Physical Assault, Hate Crime",
    "Source Name": "Google News",
    "Source URL": "https://news.google.com/rss/articles/CBMi4wFBVV95cUxNampSYkJRbkxhUUM2eU9BSHFzX3dBNkFPek1GWGRpNzZnenNXMzFuRWpVS1MyVlBEelJZNkNTM1QzTjQyZGZWUzM0WWp1Q2h6X3hEbjVINVNrc2g0NDFGYS1rdDJSWC1ZdTJuZUpLdjlWMjl3bVpQRWw5YXgzSXN2UTBFSWZIalNDeG9wMi1EVWI2SG5XMDg1SW5qd05hT0FOMElrLVN0ajYxUldDaXBsbHlnak5HY0djZTRDWjVWS2ItWjMydWFSYUFydjJhdjl0TlhLM0dEejhWSnpleWFfbjNqQQ?oc=5",
    "Latitude": "8.7642",
    "Longitude": "78.1348"
  },
  {
    "Incident ID": "011",
    "Title": "Mock Incident in Pune",
    "Date of Incident": "2024-04-15",
    "Location": "Pune",
    "State": "Maharashtra",
    "Victim Community": "Minority",
    "Incident Type": "Verbal Abuse",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/11",
    "Latitude": "18.5204",
    "Longitude": "73.8567"
  },
  {
    "Incident ID": "012",
    "Title": "Mock Incident in Surat",
    "Date of Incident": "2024-04-10",
    "Location": "Surat",
    "State": "Gujarat",
    "Victim Community": "Dalit",
    "Incident Type": "Property Damage",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/12",
    "Latitude": "21.1702",
    "Longitude": "72.8311"
  },
  {
    "Incident ID": "013",
    "Title": "Mock Incident in Kanpur",
    "Date of Incident": "2024-04-05",
    "Location": "Kanpur",
    "State": "Uttar Pradesh",
    "Victim Community": "Adivasi",
    "Incident Type": "Social Boycott",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/13",
    "Latitude": "26.4499",
    "Longitude": "80.3319"
  },
  {
    "Incident ID": "014",
    "Title": "Mock Incident in Nagpur",
    "Date of Incident": "2024-03-28",
    "Location": "Nagpur",
    "State": "Maharashtra",
    "Victim Community": "Dalit",
    "Incident Type": "Police Inaction",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/14",
    "Latitude": "21.1458",
    "Longitude": "79.0882"
  },
  {
    "Incident ID": "015",
    "Title": "Mock Incident in Indore",
    "Date of Incident": "2024-03-20",
    "Location": "Indore",
    "State": "Madhya Pradesh",
    "Victim Community": "Minority",
    "Incident Type": "Hate Speech",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/15",
    "Latitude": "22.7196",
    "Longitude": "75.8577"
  },
  {
    "Incident ID": "016",
    "Title": "Mock Incident in Thane",
    "Date of Incident": "2024-03-15",
    "Location": "Thane",
    "State": "Maharashtra",
    "Victim Community": "Dalit",
    "Incident Type": "Physical Assault",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/16",
    "Latitude": "19.2183",
    "Longitude": "72.9781"
  },
  {
    "Incident ID": "017",
    "Title": "Mock Incident in Ludhiana",
    "Date of Incident": "2024-03-10",
    "Location": "Ludhiana",
    "State": "Punjab",
    "Victim Community": "Dalit",
    "Incident Type": "Discrimination",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/17",
    "Latitude": "30.9010",
    "Longitude": "75.8573"
  },
  {
    "Incident ID": "018",
    "Title": "Mock Incident in Agra",
    "Date of Incident": "2024-03-05",
    "Location": "Agra",
    "State": "Uttar Pradesh",
    "Victim Community": "Minority",
    "Incident Type": "Harassment",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/18",
    "Latitude": "27.1767",
    "Longitude": "78.0081"
  },
  {
    "Incident ID": "019",
    "Title": "Mock Incident in Nashik",
    "Date of Incident": "2024-02-28",
    "Location": "Nashik",
    "State": "Maharashtra",
    "Victim Community": "Adivasi",
    "Incident Type": "Violence",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/19",
    "Latitude": "20.0006",
    "Longitude": "73.7898"
  },
  {
    "Incident ID": "020",
    "Title": "Mock Incident in Vadodara",
    "Date of Incident": "2024-02-20",
    "Location": "Vadodara",
    "State": "Gujarat",
    "Victim Community": "Dalit",
    "Incident Type": "Social Boycott",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/20",
    "Latitude": "22.3072",
    "Longitude": "73.1812"
  },
  {
    "Incident ID": "021",
    "Title": "Mock Incident in Ghaziabad",
    "Date of Incident": "2024-02-15",
    "Location": "Ghaziabad",
    "State": "Uttar Pradesh",
    "Victim Community": "Minority",
    "Incident Type": "Property Damage",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/21",
    "Latitude": "28.6692",
    "Longitude": "77.4538"
  },
  {
    "Incident ID": "022",
    "Title": "Mock Incident in Patna",
    "Date of Incident": "2024-02-10",
    "Location": "Patna",
    "State": "Bihar",
    "Victim Community": "Dalit",
    "Incident Type": "Physical Assault",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/22",
    "Latitude": "25.5941",
    "Longitude": "85.1376"
  },
  {
    "Incident ID": "023",
    "Title": "Mock Incident in Rajkot",
    "Date of Incident": "2024-01-25",
    "Location": "Rajkot",
    "State": "Gujarat",
    "Victim Community": "Adivasi",
    "Incident Type": "Violence",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/23",
    "Latitude": "22.3039",
    "Longitude": "70.8022"
  },
  {
    "Incident ID": "024",
    "Title": "Mock Incident in Meerut",
    "Date of Incident": "2024-01-20",
    "Location": "Meerut",
    "State": "Uttar Pradesh",
    "Victim Community": "Dalit",
    "Incident Type": "Harassment",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/24",
    "Latitude": "28.9845",
    "Longitude": "77.7064"
  },
  {
    "Incident ID": "025",
    "Title": "Mock Incident in Kalyan-Dombivli",
    "Date of Incident": "2024-01-15",
    "Location": "Kalyan",
    "State": "Maharashtra",
    "Victim Community": "Minority",
    "Incident Type": "Discrimination",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/25",
    "Latitude": "19.2396",
    "Longitude": "73.1296"
  },
  {
    "Incident ID": "026",
    "Title": "Mock Incident in Vasai-Virar",
    "Date of Incident": "2024-01-10",
    "Location": "Virar",
    "State": "Maharashtra",
    "Victim Community": "Dalit",
    "Incident Type": "Police Inaction",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/26",
    "Latitude": "19.4619",
    "Longitude": "72.8105"
  },
  {
    "Incident ID": "027",
    "Title": "Mock Incident in Varanasi",
    "Date of Incident": "2024-01-05",
    "Location": "Varanasi",
    "State": "Uttar Pradesh",
    "Victim Community": "Adivasi",
    "Incident Type": "Social Boycott",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/27",
    "Latitude": "25.3176",
    "Longitude": "82.9739"
  },
  {
    "Incident ID": "028",
    "Title": "Mock Incident in Srinagar",
    "Date of Incident": "2023-12-28",
    "Location": "Srinagar",
    "State": "Jammu and Kashmir",
    "Victim Community": "Minority",
    "Incident Type": "Property Damage",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/28",
    "Latitude": "34.0837",
    "Longitude": "74.7973"
  },
  {
    "Incident ID": "029",
    "Title": "Mock Incident in Aurangabad",
    "Date of Incident": "2023-12-20",
    "Location": "Aurangabad",
    "State": "Maharashtra",
    "Victim Community": "Dalit",
    "Incident Type": "Verbal Abuse",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/29",
    "Latitude": "19.8762",
    "Longitude": "75.3433"
  },
  {
    "Incident ID": "030",
    "Title": "Mock Incident in Dhanbad",
    "Date of Incident": "2023-12-15",
    "Location": "Dhanbad",
    "State": "Jharkhand",
    "Victim Community": "Adivasi",
    "Incident Type": "Hate Speech",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/30",
    "Latitude": "23.7957",
    "Longitude": "86.4304"
  },
  {
    "Incident ID": "031",
    "Title": "Mock Incident in Amritsar",
    "Date of Incident": "2023-12-10",
    "Location": "Amritsar",
    "State": "Punjab",
    "Victim Community": "Dalit",
    "Incident Type": "Physical Assault",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/31",
    "Latitude": "31.6340",
    "Longitude": "74.8723"
  },
  {
    "Incident ID": "032",
    "Title": "Mock Incident in Navi Mumbai",
    "Date of Incident": "2023-12-05",
    "Location": "Navi Mumbai",
    "State": "Maharashtra",
    "Victim Community": "Minority",
    "Incident Type": "Discrimination",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/32",
    "Latitude": "19.0330",
    "Longitude": "73.0297"
  },
  {
    "Incident ID": "033",
    "Title": "Mock Incident in Allahabad",
    "Date of Incident": "2023-11-28",
    "Location": "Allahabad",
    "State": "Uttar Pradesh",
    "Victim Community": "Dalit",
    "Incident Type": "Harassment",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/33",
    "Latitude": "25.4358",
    "Longitude": "81.8463"
  },
  {
    "Incident ID": "034",
    "Title": "Mock Incident in Ranchi",
    "Date of Incident": "2023-11-20",
    "Location": "Ranchi",
    "State": "Jharkhand",
    "Victim Community": "Adivasi",
    "Incident Type": "Violence",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/34",
    "Latitude": "23.3441",
    "Longitude": "85.3096"
  },
  {
    "Incident ID": "035",
    "Title": "Mock Incident in Howrah",
    "Date of Incident": "2023-11-15",
    "Location": "Howrah",
    "State": "West Bengal",
    "Victim Community": "Dalit",
    "Incident Type": "Social Boycott",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/35",
    "Latitude": "22.5958",
    "Longitude": "88.2636"
  },
  {
    "Incident ID": "036",
    "Title": "Mock Incident in Coimbatore",
    "Date of Incident": "2023-11-10",
    "Location": "Coimbatore",
    "State": "Tamil Nadu",
    "Victim Community": "Minority",
    "Incident Type": "Property Damage",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/36",
    "Latitude": "11.0168",
    "Longitude": "76.9558"
  },
  {
    "Incident ID": "037",
    "Title": "Mock Incident in Jabalpur",
    "Date of Incident": "2023-11-05",
    "Location": "Jabalpur",
    "State": "Madhya Pradesh",
    "Victim Community": "Adivasi",
    "Incident Type": "Verbal Abuse",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/37",
    "Latitude": "23.1815",
    "Longitude": "79.9864"
  },
  {
    "Incident ID": "038",
    "Title": "Mock Incident in Gwalior",
    "Date of Incident": "2023-10-28",
    "Location": "Gwalior",
    "State": "Madhya Pradesh",
    "Victim Community": "Dalit",
    "Incident Type": "Hate Speech",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/38",
    "Latitude": "26.2183",
    "Longitude": "78.1828"
  },
  {
    "Incident ID": "039",
    "Title": "Mock Incident in Vijayawada",
    "Date of Incident": "2023-10-20",
    "Location": "Vijayawada",
    "State": "Andhra Pradesh",
    "Victim Community": "Minority",
    "Incident Type": "Physical Assault",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/39",
    "Latitude": "16.5062",
    "Longitude": "80.6480"
  },
  {
    "Incident ID": "040",
    "Title": "Mock Incident in Jodhpur",
    "Date of Incident": "2023-10-15",
    "Location": "Jodhpur",
    "State": "Rajasthan",
    "Victim Community": "Dalit",
    "Incident Type": "Discrimination",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/40",
    "Latitude": "26.2389",
    "Longitude": "73.0243"
  },
  {
    "Incident ID": "041",
    "Title": "Mock Incident in Madurai",
    "Date of Incident": "2023-10-10",
    "Location": "Madurai",
    "State": "Tamil Nadu",
    "Victim Community": "Adivasi",
    "Incident Type": "Harassment",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/41",
    "Latitude": "9.9252",
    "Longitude": "78.1198"
  },
  {
    "Incident ID": "042",
    "Title": "Mock Incident in Raipur",
    "Date of Incident": "2023-10-05",
    "Location": "Raipur",
    "State": "Chhattisgarh",
    "Victim Community": "Dalit",
    "Incident Type": "Violence",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/42",
    "Latitude": "21.2514",
    "Longitude": "81.6296"
  },
  {
    "Incident ID": "043",
    "Title": "Mock Incident in Kota",
    "Date of Incident": "2023-09-28",
    "Location": "Kota",
    "State": "Rajasthan",
    "Victim Community": "Minority",
    "Incident Type": "Police Inaction",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/43",
    "Latitude": "25.2138",
    "Longitude": "75.8648"
  },
  {
    "Incident ID": "044",
    "Title": "Mock Incident in Guwahati",
    "Date of Incident": "2023-09-20",
    "Location": "Guwahati",
    "State": "Assam",
    "Victim Community": "Adivasi",
    "Incident Type": "Social Boycott",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/44",
    "Latitude": "26.1445",
    "Longitude": "91.7362"
  },
  {
    "Incident ID": "045",
    "Title": "Mock Incident in Chandigarh",
    "Date of Incident": "2023-09-15",
    "Location": "Chandigarh",
    "State": "Chandigarh",
    "Victim Community": "Dalit",
    "Incident Type": "Property Damage",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/45",
    "Latitude": "30.7333",
    "Longitude": "76.7794"
  },
  {
    "Incident ID": "046",
    "Title": "Mock Incident in Solapur",
    "Date of Incident": "2023-09-10",
    "Location": "Solapur",
    "State": "Maharashtra",
    "Victim Community": "Minority",
    "Incident Type": "Verbal Abuse",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/46",
    "Latitude": "17.6599",
    "Longitude": "75.9064"
  },
  {
    "Incident ID": "047",
    "Title": "Mock Incident in Hubli-Dharwad",
    "Date of Incident": "2023-09-05",
    "Location": "Hubli",
    "State": "Karnataka",
    "Victim Community": "Adivasi",
    "Incident Type": "Hate Speech",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/47",
    "Latitude": "15.3647",
    "Longitude": "75.1239"
  },
  {
    "Incident ID": "048",
    "Title": "Mock Incident in Bareilly",
    "Date of Incident": "2023-08-28",
    "Location": "Bareilly",
    "State": "Uttar Pradesh",
    "Victim Community": "Dalit",
    "Incident Type": "Physical Assault",
    "Source Name": "Test Source",
    "Source URL": "https://example.com/48",
    "Latitude": "28.3670",
    "Longitude": "79.4304"
  }
];

// Export the mock data
if (typeof module !== 'undefined' && module.exports) {
  module.exports = mockData;
} 